CREATE DATABASE IF NOT EXISTS `PAYMENT_SYSTEM`;

CREATE TABLE IF NOT EXISTS `PAYMENT_SYSTEM`.`payment_system` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `user_id` INT NOT NULL,
  `amount` INT NOT NULL,
  `date` DATETIME NOT NULL,
  `status` INT NOT NULL,
  PRIMARY KEY (`id`)
);

CREATE TABLE IF NOT EXISTS `PAYMENT_SYSTEM`.`user` (
	`id` INT NOT NULL AUTO_INCREMENT UNIQUE,
	`email` VARCHAR(255) NOT NULL UNIQUE,
	`password` VARCHAR(255) NOT NULL,
	`name` VARCHAR(255) NOT NULL,
	`firstname` VARCHAR(255) NOT NULL,
	`created_at` DATETIME DEFAULT NOW(),
	PRIMARY KEY (`id`,`email`)
);